version: '3.9'

services:
  aggregator:
    build: .
    depends_on:
      - db-local
    ports:
      - 8000:8000
      - 9229:9229 # debugging
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      PORT: ${SERVER_PORT}
      NODE_ENV: ${NODE_ENV}

  db-local:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
